Repository octokit/plugin-throttling.js, pull requests merged in 2021-06, with the labels that each got.

#409 fix: package.json description
  package.json
Labels: bug

#412 fix(typescript): return `{}` instead of `void`
  src/index.ts
Labels: bug, typescript

#413 feat: `error.response`
  package-lock.json
  package.json
  src/index.ts
  src/wrap-request.ts
  test/octokit.ts
Labels: feature

#416 fix: handle full URLs for GraphQL and Search request
  src/index.ts
  src/wrap-request.ts
  test/plugin.test.ts
  test/retry.test.ts
Labels: bug

#418 build(openapi-updates): use github-openapi-graphql-query
  package-lock.json
  package.json
  scripts/update-endpoints/fetch-json.js
Labels: maintenance
